language: python

python:
  - "2.7"

env:
  - ANSIBLE_VERSION=2.2.0.0
  - ANSIBLE_VERSION=2.3.0.0

install:
  - pip install flake8
  - pip install pytest
  - pip install -q ansible==$ANSIBLE_VERSION

script:
  - pytest tests/
  - flake8
